from .inline_kb_menu_main import ikb_menu_main
from .inline_kb_menu_zvyazatysya import ikb_menu_zvyazatysya
from .inline_kb_menu_magistracy import ikb_menu_magistracy
from .inline_kb_menu_bachelor import ikb_menu_bachelor
from .inline_kb_menu_osvitni import ikb_menu_osvitni
